/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author atul_
 */
public class Feedback extends javax.swing.JPanel {

    /**
     * Creates new form Feedback
     */
    public Feedback() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setText("Doctor's Name");
        add(jLabel1);
        jLabel1.setBounds(10, 120, 114, 27);

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Doctor's Appointment");
        add(jLabel4);
        jLabel4.setBounds(0, 0, 450, 41);

        jTextField1.setText("jTextField1");
        add(jTextField1);
        jTextField1.setBounds(130, 120, 202, 27);

        jLabel2.setText("Patient's name");
        add(jLabel2);
        jLabel2.setBounds(10, 170, 103, 26);

        jTextField2.setText("jTextField2");
        add(jTextField2);
        jTextField2.setBounds(130, 170, 199, 26);

        jLabel3.setText("Ratings");
        add(jLabel3);
        jLabel3.setBounds(10, 230, 83, 14);

        jLabel5.setText("Comments");
        add(jLabel5);
        jLabel5.setBounds(10, 280, 50, 14);

        jTextField3.setText("jTextField3");
        add(jTextField3);
        jTextField3.setBounds(130, 220, 199, 25);

        jTextField4.setText("jTextField4");
        add(jTextField4);
        jTextField4.setBounds(130, 270, 199, 29);

        jButton1.setText("Home");
        add(jButton1);
        jButton1.setBounds(10, 60, 59, 23);

        jButton2.setText("Booking Request");
        add(jButton2);
        jButton2.setBounds(100, 60, 113, 23);

        jButton3.setText("ViewFeedback");
        jButton3.setActionCommand("View Feedback");
        add(jButton3);
        jButton3.setBounds(250, 60, 101, 23);

        jButton4.setText("Logout");
        add(jButton4);
        jButton4.setBounds(380, 60, 65, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\images\\docc.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        add(jLabel6);
        jLabel6.setBounds(0, 0, 550, 490);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
